language: ruby
sudo: false
branches:
    only:
        - source
rvm:
    - 2.1.5
install:
    - gem install --no-rdoc --no-ri bundler jekyll rake
script:
    - rake generate
after_success:
    - rake publish
env:
    global:
        secure: g6Ug9uewpGYoiOLSj0MPL6YpkfyHOnXstHZL5dP+QvWRRi58Qauqg5LlCWJWFxM1qequyaibR8ToCrmuEU3quYoMu8h8QetpzrsUqFX6HBmCblrU2nQA8knwnghlNaCpB/pMx78q0vADqoc+Mw1Zsb/ABXWRUFwSeS2DRmr2tA0=
